version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres-persistence
    environment:
      - POSTGRES_DB=app-node-react
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    volumes:
      # Mac
      #- ~/Documents:/var/lib/postgres/data
      # Windows
      - C:\:/var/lib/postgres/data 
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "9092:5432"